DROP TABLE IF EXISTS posts;

CREATE TABLE announcements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    announcementText TEXT NOT NULL
);
